# Generated by Django 3.2.5 on 2021-08-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that email already exists.'}, max_length=30, unique=True),
        ),
    ]
